header
snkrylova/Tennis pull request #1
Opened 2023-02-09 08:57 UTC by snkrylova

2023-02-09 22:27 UTC, pavelsokolov21 commented
Предлагаю задать такую архитектуру твоего приложения, чтобы проще было ориентироваться:
```
|__index.html
|__assets/
    |__images/
    |__icons/
|__styles
    |__fonts.css
    |__main.css
    |__normalize.css
```

2023-02-09 22:41 UTC, pavelsokolov21 requested changes

2023-02-09 22:41 UTC, pavelsokolov21 commented on font-family
> +@font-face {
думаю, что этот файл должен иметь расширение `font-family.css`

2023-02-09 22:41 UTC, pavelsokolov21 commented on font-family
> +@font-face {
Все эти шрифты можно подключить с сайта [Google Fonts](https://fonts.google.com/) в HTML с помощью тега `link`. Так мы будем больше уверены в том, что шрифты у юзера будут. Сейчас ты полагаешься на локальные шрифты

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +        <header class="header-main-child">
`header` не может лежать в другом `header`. Это может быть обычный `div`

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +        <div class="container-cards-info">
выглядит не как обычный `div`, а как список `ul li`  со стороны семантики

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +              Петербургский <br />
лучше не играться так с `br`, потому что сложнее будет работать с адаптивностью. Лучше ограничить контейнер текста по ширине с помощь `max-width`.

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +                Посмотрите видео <br />
То же самое про `br`

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +    <header class="header-main">
А будет `header-not-main`? :) Лучше использовать более логичные названия

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +        <header class="header-main-child">
Аналогично про `header-main`

2023-02-09 22:41 UTC, pavelsokolov21 commented on style.css
> +  position: absolute;
зачем тут работа через абсолют? Также ты тут используешь маржины, они же не работают с абсолютом?

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +        <header class="header-main-child">
Это вынести в основной хедер

2023-02-09 22:41 UTC, pavelsokolov21 commented on index.html
> +        <div class="header-main-container">
Это отдельная секция, которая будет в `<section class="banner">`. То есть, структура будет 
```html
<body>
  <header>
    <div class="container"></div>
  </header>
   <section class="banner">
     <div class="container"></div>
   </section>
</body>
```

2023-02-10 08:48 UTC, snkrylova commented on index.html
> +        <div class="header-main-container">
А почему мы не делаем эту секцию в шапке?

2023-02-10 08:48 UTC, snkrylova commented on style.css
> +  position: absolute;
В таком сочетании выглядело наименее коряво, чем в любом другом)) в этом месте и был главный косяк, про который писала

2023-02-10 09:53 UTC, pavelsokolov21 commented on style.css
> +  position: absolute;
я потом скачаю репу и посмотрю. Выглядит так, что не нужно использовать абсолют

2023-02-10 09:53 UTC, pavelsokolov21 commented on index.html
> +        <header class="header-main-child">
ниже описано, какая должна быть структура
```html
<body>
  <header>
    <div class="container"></div>
  </header>
   <section class="banner">
     <div class="container"></div>
   </section>
</body>
```

2023-02-10 09:54 UTC, pavelsokolov21 commented on index.html
> +        <div class="header-main-container">
потому что это две отдельные секции со стороны семантики

2023-02-16 15:45 UTC, pavelsokolov21 requested changes

2023-02-16 15:45 UTC, pavelsokolov21 commented on styles/style.css
> +  /* margin-left: 0; */
убрать комментарии

2023-02-16 19:08 UTC, merged